const OneRound = `[
    {
       "Name":"<br>Played at Luttrellstown Castle (Main)",
       "Competitions":[
          {
             "Name":"Sunday Open Singles Stableford 18 Holes",
             "Date":"24 Mar 19",
             "NumHolesPlayed":18,
             "Holes":[
                {
                   "Number":1,
                   "Result":"Par",
                   "Score":"4"
                },
                {
                   "Number":2,
                   "Result":"Birde",
                   "Score":"3"
                },
                {
                   "Number":3,
                   "Result":"Par",
                   "Score":"5"
                },
                {
                   "Number":4,
                   "Result":"Par",
                   "Score":"3"
                },
                {
                   "Number":5,
                   "Result":"Par",
                   "Score":"4"
                },
                {
                   "Number":6,
                   "Result":"Bogey",
                   "Score":"4"
                },
                {
                   "Number":7,
                   "Result":"Par",
                   "Score":"4"
                },
                {
                   "Number":8,
                   "Result":"Bogey",
                   "Score":"5"
                },
                {
                   "Number":9,
                   "Result":"Par",
                   "Score":"5"
                },
                {
                   "Number":10,
                   "Result":"Scratch",
                   "Score":"NR"
                },
                {
                   "Number":11,
                   "Result":"Bogey",
                   "Score":"6"
                },
                {
                   "Number":12,
                   "Result":"Bogey",
                   "Score":"5"
                },
                {
                   "Number":13,
                   "Result":"Par",
                   "Score":"3"
                },
                {
                   "Number":14,
                   "Result":"Bogey",
                   "Score":"5"
                },
                {
                   "Number":15,
                   "Result":"Bogey",
                   "Score":"4"
                },
                {
                   "Number":16,
                   "Result":"Par",
                   "Score":"4"
                },
                {
                   "Number":17,
                   "Result":"Par",
                   "Score":"5"
                },
                {
                   "Number":18,
                   "Result":"Par",
                   "Score":"4"
                }
             ]
          }
       ],
       "CourseInfo":{
          "Holes":[
             {
                "Number":1,
                "Par":4
             },
             {
                "Number":2,
                "Par":4
             },
             {
                "Number":3,
                "Par":5
             },
             {
                "Number":4,
                "Par":3
             },
             {
                "Number":5,
                "Par":4
             },
             {
                "Number":6,
                "Par":3
             },
             {
                "Number":7,
                "Par":4
             },
             {
                "Number":8,
                "Par":4
             },
             {
                "Number":9,
                "Par":5
             },
             {
                "Number":10,
                "Par":4
             },
             {
                "Number":11,
                "Par":5
             },
             {
                "Number":12,
                "Par":4
             },
             {
                "Number":13,
                "Par":3
             },
             {
                "Number":14,
                "Par":4
             },
             {
                "Number":15,
                "Par":3
             },
             {
                "Number":16,
                "Par":4
             },
             {
                "Number":17,
                "Par":5
             },
             {
                "Number":18,
                "Par":4
             }
          ]
       }
    }
 ]`

 export default OneRound